# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lumitest
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Storage for Screenshots
storage.location=static/screenshots

# Async configuration
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
