spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lumitest
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10

storage:
  location: src/main/resources/static/screenshots
